checks:
    php:
        code_rating: true
        duplication: true
build:
  tests:
    override:
      -
        command: './vendor/bin/phpunit -c config/ --coverage-clover=coverage'
        coverage:
            file: 'coverage'
            format: 'clover'
