#!/usr/bin/php
<?php

require_once './vendor/autoload.php';

use Doctrine\Common\Annotations\AnnotationRegistry;
use Symfony\Component\Console\Application;

AnnotationRegistry::registerLoader('class_exists');

$application = new Application();
$application->add(new \Cp\Command\SnifferTrainingCommand());

$application->run();
