services:
# External services
  ics.calendar_stream:
    class: Jsvrcek\ICS\CalendarStream
  ics.utility.formater:
    class: Jsvrcek\ICS\Utility\Formatter
  ics.calendar_export:
    class: Jsvrcek\ICS\CalendarExport
    arguments: ["@ics.calendar_stream", "@ics.utility.formater"]
  phphtml.parser.dom:
    class: PHPHtmlParser\Dom
  jms.serializer.builder:
    class: JMS\Serializer\SerializerBuilder
    factory: ['JMS\Serializer\SerializerBuilder', create]
  jms.serializer:
    class: JMS\Serializer\Serializer
    factory: ['@jms.serializer.builder', build]
# Cp services
  cp.calendar.buider.calendar_event:
    class: Cp\Calendar\Builder\CalendarEventBuilder
  cp.calendar.builder.calendar:
    class: Cp\Calendar\Builder\CalendarBuilder
    arguments: ["@ics.calendar_export", "@cp.calendar.buider.calendar_event"]
  cp.parser.plan:
    class: Cp\Parser\PlanParser
    arguments: ["@phphtml.parser.dom"]
