parameters:
  url.base: "http://www.conseils-courseapied.com"
  url.types: "http://www.conseils-courseapied.com/plan-entrainement.html"
  memcache.host: "127.0.0.1"
  memcache.port: 11211

services:
# External services
  ics.calendar_stream:
    class: Jsvrcek\ICS\CalendarStream
  ics.utility.formater:
    class: Jsvrcek\ICS\Utility\Formatter
  ics.calendar_export:
    class: Jsvrcek\ICS\CalendarExport
    arguments: ["@ics.calendar_stream", "@ics.utility.formater"]
  phphtml.parser.dom:
    class: PHPHtmlParser\Dom
  jms.serializer.builder:
    class: JMS\Serializer\SerializerBuilder
    factory: ['JMS\Serializer\SerializerBuilder', create]
  jms.serializer:
    class: JMS\Serializer\Serializer
    factory: ['@jms.serializer.builder', build]
  cocur.slugify:
    class: Cocur\Slugify\Slugify
  memcached:
    class: Memcached
    calls:
      - ["addServer", ["%memcache.host%", "%memcache.port%"]]
  doctrine.cache:
    class: Doctrine\Common\Cache\MemcachedCache
    calls:
      - ["setMemcached", ["@memcached"]]

# Cp services
  # Transformer
  cp.transformer.url:
    class: Cp\Transformer\UrlTransformer
    arguments: ["%url.base%"]
  # Managers
  cp.manager.plan:
    class: Cp\Manager\PlanManager
    arguments: ["@cp.parser.plan", "@cp.transformer.url", "@jms.serializer"]
  cp.manager.type:
    class: Cp\Manager\TypeManager
    arguments: ["@cp.parser.type", "%url.types%", "@doctrine.cache"]
  # Provider
  cp.provider.type:
    class: Cp\Provider\TypeProvider
  cp.provider.plan:
    class: Cp\Provider\PlanProvider
    arguments: ["@cp.manager.plan"]
  # Builders
  cp.calendar.buider.calendar_event:
    class: Cp\Calendar\Builder\CalendarEventBuilder
  cp.calendar.builder.calendar:
    class: Cp\Calendar\Builder\CalendarBuilder
    arguments: ["@ics.calendar_export", "@cp.calendar.buider.calendar_event"]
  # Parser
  cp.http.parser.header:
    class: Cp\Http\HeaderParser
  cp.parser.plan:
    class: Cp\Parser\PlanParser
    arguments: ["@phphtml.parser.dom", "@cp.http.parser.header"]
  cp.parser.type:
    class: Cp\Parser\TypeParser
    arguments: ["@phphtml.parser.dom"]
  cp.cap_sniffer:
    class: Cp\CapSniffer
    arguments: ["@cp.provider.type", "@cp.provider.plan", "@cp.calendar.builder.calendar", "@cocur.slugify"]
